server:
  port: 8080
spring:
  application:
    name: web
  profiles:
    active: dev
  datasource:
    driver-class-name: ${oldmerman.datasource.driver-class-name}
    url: jdbc:mysql://${oldmerman.datasource.host}:${oldmerman.datasource.port}/${oldmerman.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${oldmerman.datasource.username}
    password: ${oldmerman.datasource.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: ${oldmerman.redis.host}
      port: ${oldmerman.redis.port}
      database: ${oldmerman.redis.database}
      timeout: 5s